[package]
name = "cdg_renderer"
version = "0.1.0"
authors = ["TQ Hirsch <thequux@thequux.com>"]
description = "CD+G renderer"
repository = "https://github.com/thequux/qaraoke"
license = "ISC"

keywords = ["cdg", "cd+g", "karaoke"]


[dependencies]
cdg = { path = "../cdg" }
image = "0.10"

